import type { PaymentMethod } from "@/lib/payment-methods"

// Mock financial data for demonstration
export const mockTransactions = [
  // January 2024
  {
    id: "1",
    date: "2024-01-01",
    amount: 3500,
    description: "Monthly Salary",
    category: "Salary",
    type: "income",
    paymentMethod: "bank_transfer" as PaymentMethod,
  },
  {
    id: "2",
    date: "2024-01-01",
    amount: 1200,
    description: "Rent Payment",
    category: "Housing",
    type: "expense",
    paymentMethod: "bank_transfer" as PaymentMethod,
  },
  {
    id: "3",
    date: "2024-01-05",
    amount: 85.75,
    description: "Grocery Shopping",
    category: "Food",
    type: "expense",
    paymentMethod: "debit_card" as PaymentMethod,
  },
  {
    id: "4",
    date: "2024-01-10",
    amount: 500,
    description: "Freelance Project",
    category: "Freelance",
    type: "income",
    paymentMethod: "digital_wallet" as PaymentMethod,
  },
  {
    id: "5",
    date: "2024-01-15",
    amount: 120,
    description: "Electric Bill",
    category: "Utilities",
    type: "expense",
    paymentMethod: "credit_card" as PaymentMethod,
  },
  {
    id: "6",
    date: "2024-01-20",
    amount: 45.99,
    description: "Internet Subscription",
    category: "Utilities",
    type: "expense",
    paymentMethod: "credit_card" as PaymentMethod,
  },
  {
    id: "7",
    date: "2024-01-25",
    amount: 60,
    description: "Dinner with Friends",
    category: "Entertainment",
    type: "expense",
    paymentMethod: "cash" as PaymentMethod,
  },

  // February 2024
  {
    id: "8",
    date: "2024-02-01",
    amount: 3500,
    description: "Monthly Salary",
    category: "Salary",
    type: "income",
    paymentMethod: "bank_transfer" as PaymentMethod,
  },
  {
    id: "9",
    date: "2024-02-01",
    amount: 1200,
    description: "Rent Payment",
    category: "Housing",
    type: "expense",
    paymentMethod: "bank_transfer" as PaymentMethod,
  },
  {
    id: "10",
    date: "2024-02-05",
    amount: 92.3,
    description: "Grocery Shopping",
    category: "Food",
    type: "expense",
    paymentMethod: "debit_card" as PaymentMethod,
  },
  {
    id: "11",
    date: "2024-02-10",
    amount: 750,
    description: "Freelance Project",
    category: "Freelance",
    type: "income",
    paymentMethod: "check" as PaymentMethod,
  },
  {
    id: "12",
    date: "2024-02-15",
    amount: 110,
    description: "Electric Bill",
    category: "Utilities",
    type: "expense",
    paymentMethod: "credit_card" as PaymentMethod,
  },
  {
    id: "13",
    date: "2024-02-20",
    amount: 45.99,
    description: "Internet Subscription",
    category: "Utilities",
    type: "expense",
    paymentMethod: "credit_card" as PaymentMethod,
  },
  {
    id: "14",
    date: "2024-02-25",
    amount: 80,
    description: "Movie Night",
    category: "Entertainment",
    type: "expense",
    paymentMethod: "debit_card" as PaymentMethod,
  },

  // March 2024
  {
    id: "15",
    date: "2024-03-01",
    amount: 3500,
    description: "Monthly Salary",
    category: "Salary",
    type: "income",
    paymentMethod: "bank_transfer" as PaymentMethod,
  },
  {
    id: "16",
    date: "2024-03-01",
    amount: 1200,
    description: "Rent Payment",
    category: "Housing",
    type: "expense",
    paymentMethod: "bank_transfer" as PaymentMethod,
  },
  {
    id: "17",
    date: "2024-03-05",
    amount: 105.5,
    description: "Grocery Shopping",
    category: "Food",
    type: "expense",
    paymentMethod: "cash" as PaymentMethod,
  },
  {
    id: "18",
    date: "2024-03-10",
    amount: 1000,
    description: "Consulting Work",
    category: "Freelance",
    type: "income",
    paymentMethod: "digital_wallet" as PaymentMethod,
  },
  {
    id: "19",
    date: "2024-03-15",
    amount: 130,
    description: "Electric Bill",
    category: "Utilities",
    type: "expense",
    paymentMethod: "credit_card" as PaymentMethod,
  },
  {
    id: "20",
    date: "2024-03-20",
    amount: 45.99,
    description: "Internet Subscription",
    category: "Utilities",
    type: "expense",
    paymentMethod: "credit_card" as PaymentMethod,
  },
  {
    id: "21",
    date: "2024-03-25",
    amount: 150,
    description: "Concert Tickets",
    category: "Entertainment",
    type: "expense",
    paymentMethod: "debit_card" as PaymentMethod,
  },

  // Recent days (for today/last 7 days filters)
  {
    id: "22",
    date: "2024-03-28",
    amount: 25.5,
    description: "Coffee Shop",
    category: "Food",
    type: "expense",
    paymentMethod: "cash" as PaymentMethod,
  },
  {
    id: "23",
    date: "2024-03-29",
    amount: 200,
    description: "Side Project",
    category: "Freelance",
    type: "income",
    paymentMethod: "digital_wallet" as PaymentMethod,
  },
  {
    id: "24",
    date: "2024-03-30",
    amount: 75.25,
    description: "Gas Station",
    category: "Transportation",
    type: "expense",
    paymentMethod: "credit_card" as PaymentMethod,
  },
]

export type Transaction = (typeof mockTransactions)[0]

export function replaceAllTransactions(newTransactions: Transaction[]) {
  // In a real app, this would update the database
  // For now, we'll just update the mock data
  mockTransactions.length = 0
  mockTransactions.push(...newTransactions)
}
